SchoolManagement/Models/Enrollment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int EnrollmentID { get; set; }
        public Nullable<decimal> Grade { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> LecturerId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual Lecturer Lecturer { get; set; }
    }
}

SchoolManagement/Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.Models;

namespace SchoolManagement.Controllers
{
    public class EnrollmentsController : Controller
    {
        private SchoolManagement_DBEntities db = new SchoolManagement_DBEntities();

        // GET: Enrollments
        public async Task<ActionResult> Index()
        {
            var enrollments = db.Enrollments.Include(e => e.Course).Include(e => e.Student).Include(e => e.Lecturer);
            return View(await enrollments.ToListAsync());
        }

        //Metodo para la partial view _enrollmentPartial
        public PartialViewResult _enrollmentPartial(int? courseid)
        {
            IQueryable <Enrollment> enrollments = null;
            if (courseid != null) enrollments = db.Enrollments.Where(q => q.CourseID == courseid);
            else enrollments = db.Enrollments;

            enrollments.Include(e => e.Course)
                .Include(e => e.Student);

            return PartialView(enrollments.ToList());
        }

        // GET: Enrollments/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = await db.Enrollments.FindAsync(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollments/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title");
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "LastName");
            ViewBag.LecturerId = new SelectList(db.Lecturers, "Id", "FirstName");
            return View();
        }

        // POST: Enrollments/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "EnrollmentID,Grade,CourseID,StudentID,LecturerId")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.Add(enrollment);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "LastName", enrollment.StudentID);
            ViewBag.LecturerId = new SelectList(db.Lecturers, "Id", "FirstName", enrollment.LecturerId);
            return View(enrollment);
        }

        [HttpPost]
        public async Task<JsonResult> AddStudent([Bind(Include = "CourseID,StudentID")] Enrollment enrollment)
        {
            try
            {
                var isEnrolled = db.Enrollments.Any(q => q.CourseID == enrollment.CourseID && q.StudentID == enrollment.StudentID);

                if (ModelState.IsValid && !isEnrolled)
                {
                    db.Enrollments.Add(enrollment);
                    await db.SaveChangesAsync();
                    return Json(new { IsSuccess = true, Message = "Estudiante agregado exitosamente" }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { IsSuccess = false, Message = "El estudiante no pudo ser agregado, o ya fue registrado previamente" }, 
                    JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { IsSuccess = false, Message = "Error de Sistema: Favor de comunicarse con tu Administrador" }, 
                    JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Enrollments/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = await db.Enrollments.FindAsync(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "LastName", enrollment.StudentID);
            ViewBag.LecturerId = new SelectList(db.Lecturers, "Id", "FirstName", enrollment.LecturerId);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "EnrollmentID,Grade,CourseID,StudentID,LecturerId")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "LastName", enrollment.StudentID);
            ViewBag.LecturerId = new SelectList(db.Lecturers, "Id", "FirstName", enrollment.LecturerId);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = await db.Enrollments.FindAsync(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    Enrollment enrollment = await db.Enrollments.FindAsync(id);
        //    db.Enrollments.Remove(enrollment);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("Index");
        //}
        public async Task<JsonResult> DeleteConfirmed(int id)
        {            
            try
            {
                Enrollment enrollment = await db.Enrollments.FindAsync(id);
                db.Enrollments.Remove(enrollment);
                await db.SaveChangesAsync();
                return Json(new { IsSuccess = true, Message = "Curso eliminado exitosamente" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { IsSuccess = false, Message = "El curso no pudo ser eliminado" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult GetStudents(string term)
        {
            //students es un objeto abstracto trayendo el nombre completo del estudiante y StudentID
            var students = db.Students.Select(q => new
            {
                Name = q.FirstName + " " + q.LastName,
                Id = q.StudentID
            }).Where(q => q.Name.Contains(term));
            return Json(students, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagement/Views/Enrollments/Create.cshtml
@model SchoolManagement.Models.Enrollment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*El script se puede escribir en otro archivo y referenciarse, pero para fines practicos se dejara aqui...*@
@*JQuery y Ajax*@
<script>
    //Jquery y Ajax
    //Jquery siempre empieza sus bloques asi: $(function () {});
    $(function () {
        //Asi no repetimos mas codigo
        function LoadEnrollments(cid) {
            $.ajax({
                url: '@Url.Action("_enrollmentPartial", "Enrollments")',  //Una forma de llamar a una de las secciones de la pagina, me gusta mas esta
                //url: '@Url.Action("_enrollmentPartial", "Enrollments")',  //Una forma de llamar a una de las secciones de la pagina
                dataType: 'html',  //Html porque se va a recibir un contenido html
                contentType: 'application/html; charset=utf-8',
                type: 'GET',
                data: {
                    //valor en controlador: valor en este script
                    courseid: cid
                },
                success: function (data) {
                    //Con jquery se llama al control 'data', se le agrega animaciones y se le llena con el valor data
                    $('#data').fadeOut().html(data).fadeIn();
                }
            });
        }

        //Esto se va a ejecutar apenas inicie la pagina
        var cid = $('#CourseID').val();
        LoadEnrollments(cid);

        //Funcion para un change event
        //Jquery
        $('#CourseID').change(function () {
            var cid = $('#CourseID').val();
            LoadEnrollments(cid);
            $("#failed").fadeOut('fast');
            $("#success").fadeOut('fast');
        });

        //Funcion para el autocomplete
        //Jquery
        //Student_FirstName es el EditorFor de FirstName
        $("#Student_FirstName").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/Enrollments/GetStudents",  //Otra forma de llamar a una de las secciones de la pagina
                    dataType: "json",  //Json porque se va a recibir un json
                    type: "POST",
                    data: {
                        term: request.term
                    },
                    success: function (data) {
                        console.log(data);
                        response($.map(data, function (item) {
                            return { label: item.Name, Value: item.Name, id: item.Id };
                        }));
                    }
                });
            },
            minLength: 2,
            select: function (event, query) {
                //log("Selected: " + ui.item.value + " aka " + ui.item.id);
                console.log(query);
                $("#StudentID").val(query.item.id);
            }
        });
    });

    //Se desencadena cuando la ejecucion de AddStudent sea exitosa
    //JavaScript
    function Added(res) {
        if (res.IsSuccess) {
            //Jquery
            $(function () {
                $("#failed").fadeOut('fast');
                $("#success").fadeIn('fast');
                //$("#success").append(res.Message); <-- Asi se toma el texto que regresa el json desde el controlador

                //Asi recargamos el listado, ya que por el acomodo que se tiene aqui, Added esta fuera del scope del segmento de Jquery que tenemos arriba
                //y por lo mismo no puede llamar exitosamente a LoadEnrollments
                var cid = $('#CourseID').val();
                $.ajax({
                    url: '@Url.Action("_enrollmentPartial", "Enrollments")',  //Una forma de llamar a una de las secciones de la pagina, me gusta mas esta
                    //url: '@Url.Action("_enrollmentPartial", "Enrollments")',  //Una forma de llamar a una de las secciones de la pagina
                    dataType: 'html',  //Html porque se va a recibir un contenido html
                    contentType: 'application/html; charset=utf-8',
                    type: 'GET',
                    data: {
                        //valor en controlador: valor en este script
                        courseid: cid
                    },
                    success: function (data) {
                        //Con jquery se llama al control 'data', se le agrega animaciones y se le llena con el valor data
                        $('#data').fadeOut().html(data).fadeIn();
                    }
                });
            })
        }
        else {
            Failed(res);
        }
    }

    //Se desencadena cuando la ejecucion de AddStudent tuviera errores
    //JavaScript
    function Failed(res) {
        //Jquery
        $(function () {
            $("#failed").fadeIn('fast');
            $("#success").fadeOut('fast');
            //$("#failed").append(res.Message); <-- Asi se toma el texto que regresa el json desde el controlador
        })
    }
</script>

<h2>Create</h2>

@*Como se quiere que la pagina no se recargue constantemente (la pagina no debara recargarse cada que se de de alta un enrolamiento),
se necesita una Ajax Form, y por lo mismo esto cambia de Html a Ajax*@
@*@using (Html.BeginForm())*@ 
@using (Ajax.BeginForm("AddStudent", "Enrollments", new AjaxOptions { 
    HttpMethod = "POST",
    OnSuccess = "Added",
    OnFailure = "Failure"
}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enrollment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div id="failed" class="alert alert-danger" style="display: none;">
            Ocurrio un error al agregar al Estudiante a este Curso
        </div>
        <div id="success" class="alert alert-success" style="display: none;">
            Estudiante agregado exitosamente
        </div>

        <div class="form-group">
            <label for="CourseID" class="control-label col-md-2">Curso</label>
            @*@Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="StudentID" class="control-label col-md-2">Nombre del Estudiante</label>
            @*@Html.LabelFor(model => model.Student.FirstName, "FirstName", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })*@
                @*El nombre del EditorFor toma el nombre completo de la entidad (Student), un guion bajo y el nombre del campo
            En este caso seria: Student_FirstName*@
                @Html.EditorFor(model => model.Student.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.StudentID)
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.LecturerId, "LecturerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LecturerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LecturerId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enrolar" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}

<hr/>

@*Partial View para mostrar los enrolamientos existentes y los nuevos sin que la pagina recargue, y sin volver al index de Enrollment*@
<div id="data">
    @*@Html.Action("_enrollmentPartial", "Enrollments")*@
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SchoolManagement/Views/Enrollments/Delete.cshtml
@model SchoolManagement.Models.Enrollment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    $(function () {
        function LoadEnrollments() {
            $.ajax({
                url: '@Url.Action("_enrollmentPartial", "Enrollments")',  //Una forma de llamar a una de las secciones de la pagina, me gusta mas esta
                //url: '@Url.Action("_enrollmentPartial", "Enrollments")',  //Una forma de llamar a una de las secciones de la pagina
                dataType: 'html',  //Html porque se va a recibir un contenido html
                contentType: 'application/html; charset=utf-8',
                type: 'GET',
                success: function (data) {
                    //Con jquery se llama al control 'data', se le agrega animaciones y se le llena con el valor data
                    $('#data').fadeOut().html(data).fadeIn();
                }
            });
        }

        LoadEnrollments();
    });

    //Se desencadena cuando la ejecucion de Delete sea exitosa
    //JavaScript
    function Deleted(res) {
        if (res.IsSuccess) {
            //Jquery
            $(function () {
                $("#failed").fadeOut('fast');
                $("#success").fadeIn('fast');
                $.ajax({
                    url: '@Url.Action("_enrollmentPartial", "Enrollments")',  //Una forma de llamar a una de las secciones de la pagina, me gusta mas esta
                    //url: '@Url.Action("_enrollmentPartial", "Enrollments")',  //Una forma de llamar a una de las secciones de la pagina
                    dataType: 'html',  //Html porque se va a recibir un contenido html
                    contentType: 'application/html; charset=utf-8',
                    type: 'GET',
                    success: function (data) {
                        //Con jquery se llama al control 'data', se le agrega animaciones y se le llena con el valor data
                        $('#data').fadeOut().html(data).fadeIn();
                    }
                });
            })
        }
        else {
            Failed(res);
        }
    }

    //Se desencadena cuando la ejecucion de Delete tuviera errores
    //JavaScript
    function Failed(res) {
        //Jquery
        $(function () {
            $("#failed").fadeIn('fast');
            $("#success").fadeOut('fast');
            //$("#failed").append(res.Message); <-- Asi se toma el texto que regresa el json desde el controlador
        })
    }
</script>>

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />


    @using (Ajax.BeginForm("Delete", "Enrollments", new AjaxOptions
    {
        HttpMethod = "POST",
        OnSuccess = "Deleted",
        OnFailure = "Failure"
    }))
    {
        @Html.AntiForgeryToken()

        <div id="failed" class="alert alert-danger" style="display: none;">
            Ocurrio un error al eliminar este Curso
        </div>
        <div id="success" class="alert alert-success" style="display: none;">
            Curso eliminado exitosamente
        </div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Grade)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Grade)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Course.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Course.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Student.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Student.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Lecturer.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Lecturer.FirstName)
            </dd>

        </dl>

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-block" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

@*Partial View para mostrar los enrolamientos existentes y los nuevos sin que la pagina recargue, y sin volver al index de Enrollment*@
<div id="data">
    @*@Html.Action("_enrollmentPartial", "Enrollments")*@
</div>

SchoolManagement/Views/Enrollments/Details.cshtml
@model SchoolManagement.Models.Enrollment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lecturer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lecturer.FirstName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EnrollmentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SchoolManagement/Views/Enrollments/Edit.cshtml
@model SchoolManagement.Models.Enrollment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enrollment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EnrollmentID)

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LecturerId, "LecturerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LecturerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LecturerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SchoolManagement/Views/Enrollments/Index.cshtml
@model IEnumerable<SchoolManagement.Models.Enrollment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lecturer.FirstName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Grade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lecturer.FirstName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EnrollmentID }) |
            @Html.ActionLink("Details", "Details", new { id=item.EnrollmentID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EnrollmentID })
        </td>
    </tr>
}

</table>

SchoolManagement/Views/Enrollments/_enrollmentPartial.cshtml
@model IEnumerable<SchoolManagement.Models.Enrollment>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
@if (Model.Count() < 1)
{
    <h1 class="text-center text-info">NO HAY ENROLAMIENTOS EN ESTE CURSO</h1>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course.Title)
            </th>
            <th>
                Estudiante
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Student.LastName)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.Lecturer.FirstName)
                </th>*@
            <th>Acciones</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.FirstName) @Html.DisplayFor(modelItem => item.Student.LastName)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Student.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Lecturer.FirstName)
                    </td>*@
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id=item.EnrollmentID }) |
                        @Html.ActionLink("Details", "Details", new { id=item.EnrollmentID }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.EnrollmentID })
                </td>
            </tr>
        }

    </table>

}